### ISSUE TITLE
new decives

### ISSUE THREAD

**Issue by NES8** [InderKumarRathore/UIDeviceUtil#17]
Hello,

This is de message:

This is a device which is not listed in this category. Please visit https://github.com/inderkumarrathore/UIDevice-Hardware and add a comment there.
Your device hardware string is: iPhone7,1

Thank you.

**Comment by InderKumarRathore** [comment]
Hi NES8,
Could you please tell me which device is this?
Thanks

**Comment by InderKumarRathore** [comment]
I hope you have the latest code

**Comment by NES8** [comment]
I forgot put in my Podfile for update automatically. I'm really sorry, it's my mistake. Thank you a lot!

**Comment by InderKumarRathore** [comment]
No problem dear.

**Comment by InderKumarRathore** [comment]
No problem dear.
